import { db, productsTable, pool } from "@workspace/db";

const PLACEHOLDER = "https://placehold.co/600x800/f5f5f5/999?text=PickMe";

interface SeedProduct {
  brand: string;
  name: string;
  size: string;
  price: number;
  category: "shoes" | "tops" | "bottoms" | "accessories" | "supplements";
  caption: string;
  imageUrl: string;
  imageUrls: string | null;
  badge: "new" | "sold" | "reserved" | null;
  telegramUrl: string;
  featured: boolean;
  gender: string;
  published: boolean;
  description: string | null;
  purchasePrice: number | null;
  sku: string | null;
  model: string | null;
}

function img(text: string, bg = "f5f5f5", fg = "999"): string {
  return `https://placehold.co/600x800/${bg}/${fg}?text=${encodeURIComponent(text)}`;
}

const products: SeedProduct[] = [
  // ===================== SHOES =====================
  {
    brand: "Nike",
    name: "Air Force 1 '07",
    size: "38",
    price: 8900,
    category: "shoes",
    caption: "Классика на каждый день",
    imageUrl: img("Nike AF1", "fff", "111"),
    imageUrls: JSON.stringify([img("Nike AF1", "fff", "111"), img("Nike AF1 side", "fafafa", "333")]),
    badge: "new",
    telegramUrl: "https://t.me/pickmestore",
    featured: true,
    gender: "women",
    published: true,
    description: "Легендарные Air Force 1 в белом цвете. Кожаный верх, амортизация Air-Sole. Идеальное состояние.",
    purchasePrice: 5500,
    sku: "NK-AF1-38",
    model: "CW2288-111",
  },
  {
    brand: "Adidas",
    name: "Samba OG",
    size: "39",
    price: 11200,
    category: "shoes",
    caption: "Тренд сезона",
    imageUrl: img("Adidas Samba", "f0f0f0", "222"),
    imageUrls: JSON.stringify([img("Adidas Samba", "f0f0f0", "222"), img("Samba detail", "eee", "444")]),
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: true,
    gender: "women",
    published: true,
    description: "Adidas Samba OG в черно-белой расцветке. Замшевые вставки, резиновая подошва. Состояние как новые.",
    purchasePrice: 7000,
    sku: "AD-SMB-39",
    model: "B75807",
  },
  {
    brand: "New Balance",
    name: "550",
    size: "40",
    price: 12500,
    category: "shoes",
    caption: "Ретро-баскетбол",
    imageUrl: img("NB 550", "fafafa", "333"),
    imageUrls: null,
    badge: "new",
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "unisex",
    published: true,
    description: "New Balance 550 — возвращение культовой модели 80-х. Кожа, перфорация, плоская подошва.",
    purchasePrice: 8000,
    sku: "NB-550-40",
    model: "BB550PB1",
  },
  {
    brand: "Converse",
    name: "Chuck 70 High",
    size: "37",
    price: 6500,
    category: "shoes",
    caption: "Вечная классика",
    imageUrl: img("Converse 70", "f8f8f8", "222"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "women",
    published: true,
    description: "Converse Chuck 70 с усиленной стелькой OrthoLite. Чёрный канвас, высокая посадка.",
    purchasePrice: 3500,
    sku: "CV-C70-37",
    model: "162050C",
  },
  {
    brand: "Nike",
    name: "Dunk Low Panda",
    size: "41",
    price: 10800,
    category: "shoes",
    caption: "Самая популярная расцветка",
    imageUrl: img("Dunk Panda", "fff", "111"),
    imageUrls: null,
    badge: "reserved",
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "men",
    published: true,
    description: "Nike Dunk Low в черно-белой расцветке «Панда». Кожаный верх, мягкий воротник.",
    purchasePrice: 7200,
    sku: "NK-DNK-41",
    model: "DD1391-100",
  },
  {
    brand: "Puma",
    name: "Suede Classic XXI",
    size: "38",
    price: 5400,
    category: "shoes",
    caption: "Бархатная замша",
    imageUrl: img("Puma Suede", "f3f3f3", "555"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "women",
    published: true,
    description: "Puma Suede Classic в пыльно-розовом цвете. Замшевый верх, резиновая подошва.",
    purchasePrice: 3000,
    sku: "PM-SDE-38",
    model: "374915-04",
  },

  // ===================== TOPS =====================
  {
    brand: "Zara",
    name: "Укороченный свитер",
    size: "S",
    price: 3200,
    category: "tops",
    caption: "Мягкий трикотаж",
    imageUrl: img("Zara Sweater", "f9e8e8", "a05050"),
    imageUrls: null,
    badge: "new",
    telegramUrl: "https://t.me/pickmestore",
    featured: true,
    gender: "women",
    published: true,
    description: "Укороченный свитер из мягкого трикотажа. Рукава-фонарики, круглый вырез. Цвет — пудровый розовый.",
    purchasePrice: 1800,
    sku: "ZR-SWT-S",
    model: null,
  },
  {
    brand: "H&M",
    name: "Базовая футболка oversize",
    size: "M",
    price: 1200,
    category: "tops",
    caption: "Must-have в гардеробе",
    imageUrl: img("H&M Tee", "f0f0f0", "555"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "unisex",
    published: true,
    description: "Базовая хлопковая футболка свободного кроя. Плотный хлопок 220 г/м². Белый цвет.",
    purchasePrice: 500,
    sku: "HM-TEE-M",
    model: null,
  },
  {
    brand: "Stussy",
    name: "Basic Hoodie",
    size: "L",
    price: 7800,
    category: "tops",
    caption: "Streetwear essential",
    imageUrl: img("Stussy Hoodie", "e8e8f0", "3a3a6a"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "men",
    published: true,
    description: "Худи Stussy с логотипом на груди. Плотный флис, карман-кенгуру. Тёмно-синий.",
    purchasePrice: 4500,
    sku: "ST-HOD-L",
    model: null,
  },
  {
    brand: "Uniqlo",
    name: "Рубашка оксфорд",
    size: "M",
    price: 2400,
    category: "tops",
    caption: "Casual классика",
    imageUrl: img("Uniqlo Shirt", "e8f0f5", "335577"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "men",
    published: true,
    description: "Рубашка из ткани оксфорд. Button-down воротник, slim fit. Голубой цвет.",
    purchasePrice: 1200,
    sku: "UQ-OXF-M",
    model: null,
  },
  {
    brand: "Massimo Dutti",
    name: "Блуза с бантом",
    size: "S",
    price: 4500,
    category: "tops",
    caption: "Элегантный акцент",
    imageUrl: img("MD Blouse", "fdf5f0", "8a6040"),
    imageUrls: null,
    badge: "new",
    telegramUrl: "https://t.me/pickmestore",
    featured: true,
    gender: "women",
    published: true,
    description: "Сатиновая блуза с завязкой-бантом. Свободный крой, длинный рукав. Цвет экрю.",
    purchasePrice: 2500,
    sku: "MD-BLS-S",
    model: null,
  },
  {
    brand: "Carhartt WIP",
    name: "Pocket Tee",
    size: "XL",
    price: 3800,
    category: "tops",
    caption: "Рабочий стиль",
    imageUrl: img("Carhartt Tee", "e8e4d8", "5a5040"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "men",
    published: true,
    description: "Футболка Carhartt WIP с нагрудным карманом. Плотный хлопок, прямой крой. Хаки.",
    purchasePrice: 2000,
    sku: "CH-PKT-XL",
    model: null,
  },

  // ===================== BOTTOMS =====================
  {
    brand: "Levi's",
    name: "501 Original Fit",
    size: "28/32",
    price: 7200,
    category: "bottoms",
    caption: "Эталон денима",
    imageUrl: img("Levis 501", "e8eaf0", "334466"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: true,
    gender: "women",
    published: true,
    description: "Классические джинсы Levi's 501. Прямой крой, пуговицы, средняя посадка. Тёмно-синий wash.",
    purchasePrice: 4000,
    sku: "LV-501-28",
    model: "12501-0300",
    outerSeam: 105,
    innerSeam: 78,
    riseHeight: 27,
    halfWaist: 35,
    halfHip: 47,
    halfLegOpening: 18,
  } as any,
  {
    brand: "Zara",
    name: "Широкие брюки палаццо",
    size: "S",
    price: 3900,
    category: "bottoms",
    caption: "Женственный силуэт",
    imageUrl: img("Zara Palazzo", "f0ece8", "6a5a4a"),
    imageUrls: null,
    badge: "new",
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "women",
    published: true,
    description: "Широкие брюки палаццо с высокой посадкой. Струящаяся ткань, пояс на резинке. Бежевый.",
    purchasePrice: 2000,
    sku: "ZR-PLZ-S",
    model: null,
  },
  {
    brand: "Dickies",
    name: "874 Original Work Pant",
    size: "32/32",
    price: 5600,
    category: "bottoms",
    caption: "Рабочий стиль, уличный образ",
    imageUrl: img("Dickies 874", "e5e5e0", "444433"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "men",
    published: true,
    description: "Культовые рабочие брюки Dickies 874. Прямой крой, стрелки, стойкая ткань. Чёрный.",
    purchasePrice: 3200,
    sku: "DK-874-32",
    model: "874BK",
  },
  {
    brand: "H&M",
    name: "Юбка-миди плиссе",
    size: "M",
    price: 2800,
    category: "bottoms",
    caption: "Лёгкость и движение",
    imageUrl: img("H&M Pleats", "f0e8f0", "6a4a6a"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "women",
    published: true,
    description: "Плиссированная юбка-миди на эластичном поясе. Длина ниже колена. Лавандовый цвет.",
    purchasePrice: 1400,
    sku: "HM-PLS-M",
    model: null,
  },
  {
    brand: "Nike",
    name: "Спортивные джоггеры Tech Fleece",
    size: "L",
    price: 6900,
    category: "bottoms",
    caption: "Комфорт на максимуме",
    imageUrl: img("Nike Tech", "e8e8e8", "333"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "men",
    published: true,
    description: "Джоггеры Nike Tech Fleece. Двойной флис, зауженный крой, карманы на молнии. Серый меланж.",
    purchasePrice: 4200,
    sku: "NK-TF-L",
    model: "CU4495-063",
  },

  // ===================== ACCESSORIES =====================
  {
    brand: "Ray-Ban",
    name: "Aviator Classic",
    size: "58mm",
    price: 9500,
    category: "accessories",
    caption: "Легенда авиации",
    imageUrl: img("Ray-Ban", "f5f0e5", "5a4a2a"),
    imageUrls: null,
    badge: "new",
    telegramUrl: "https://t.me/pickmestore",
    featured: true,
    gender: "unisex",
    published: true,
    description: "Очки Ray-Ban Aviator с золотой оправой и зелёными линзами G-15. В оригинальном кейсе.",
    purchasePrice: 6000,
    sku: "RB-AVI-58",
    model: "RB3025",
  },
  {
    brand: "Daniel Wellington",
    name: "Petite Sheffield",
    size: "32mm",
    price: 8200,
    category: "accessories",
    caption: "Минималистичная элегантность",
    imageUrl: img("DW Watch", "fff5f0", "8a5040"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: true,
    gender: "women",
    published: true,
    description: "Часы Daniel Wellington с чёрным кожаным ремешком и белым циферблатом. Корпус из розового золота.",
    purchasePrice: 5000,
    sku: "DW-PTT-32",
    model: "DW00100230",
  },
  {
    brand: "The North Face",
    name: "Borealis Backpack",
    size: "28L",
    price: 7400,
    category: "accessories",
    caption: "На каждый день и в поход",
    imageUrl: img("TNF Bag", "e5e8e5", "334433"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "unisex",
    published: true,
    description: "Рюкзак The North Face Borealis. Отделение для ноутбука 15\", FlexVent подвеска. Чёрный.",
    purchasePrice: 4500,
    sku: "TNF-BRL-28",
    model: "NF0A52SE",
  },
  {
    brand: "Pandora",
    name: "Браслет Moments с замком-сердцем",
    size: "17 см",
    price: 5800,
    category: "accessories",
    caption: "Подарок с душой",
    imageUrl: img("Pandora", "fdf0f5", "a05070"),
    imageUrls: null,
    badge: "new",
    telegramUrl: "https://t.me/pickmestore",
    featured: true,
    gender: "women",
    published: true,
    description: "Серебряный браслет Pandora Moments с замком в форме сердца. Серебро 925 пробы.",
    purchasePrice: 3500,
    sku: "PD-MOM-17",
    model: "599279C00",
  },
  {
    brand: "Guess",
    name: "Шарф с монограммой",
    size: "180×60 см",
    price: 4100,
    category: "accessories",
    caption: "Тёплый и стильный",
    imageUrl: img("Guess Scarf", "f0e8e0", "7a6040"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "women",
    published: true,
    description: "Шарф Guess с жаккардовой монограммой. Мягкая вискоза, бежево-коричневая гамма.",
    purchasePrice: 2200,
    sku: "GS-SCF-180",
    model: null,
  },
  {
    brand: "Calvin Klein",
    name: "Ремень с пряжкой CK",
    size: "90 см",
    price: 4600,
    category: "accessories",
    caption: "Акцент на деталях",
    imageUrl: img("CK Belt", "e8e0d8", "5a4a3a"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "unisex",
    published: true,
    description: "Кожаный ремень Calvin Klein с металлической пряжкой-логотипом. Двусторонний: чёрный/коричневый.",
    purchasePrice: 2800,
    sku: "CK-BLT-90",
    model: null,
  },

  // ===================== SUPPLEMENTS =====================
  {
    brand: "Dymatize",
    name: "ISO100 Hydrolyzed Whey",
    size: "900 г",
    price: 4800,
    category: "supplements",
    caption: "Чистый протеин",
    imageUrl: img("Dymatize ISO", "e8f0e8", "336633"),
    imageUrls: null,
    badge: null,
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "unisex",
    published: true,
    description: "Гидролизованный сывороточный протеин. 25 г белка на порцию, без лактозы. Вкус: шоколад.",
    purchasePrice: 3000,
    sku: "DM-ISO-900",
    model: null,
  },
  {
    brand: "Optimum Nutrition",
    name: "Gold Standard BCAA",
    size: "280 г",
    price: 2900,
    category: "supplements",
    caption: "Восстановление мышц",
    imageUrl: img("ON BCAA", "e5e8f0", "334466"),
    imageUrls: null,
    badge: "new",
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "unisex",
    published: true,
    description: "Аминокислоты BCAA в соотношении 2:1:1. Электролиты, витамин C. Вкус: арбуз.",
    purchasePrice: 1800,
    sku: "ON-BCAA-280",
    model: null,
  },

  // ===================== A few SOLD items =====================
  {
    brand: "Gucci",
    name: "Кроссовки Ace",
    size: "39",
    price: 28000,
    category: "shoes",
    caption: "Люкс на каждый день",
    imageUrl: img("Gucci Ace", "f8f5f0", "5a4a2a"),
    imageUrls: null,
    badge: "sold",
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "women",
    published: true,
    description: "Кроссовки Gucci Ace с фирменной полоской. Кожа, вышивка пчелы. Б/у, отличное состояние.",
    purchasePrice: 18000,
    sku: "GC-ACE-39",
    model: null,
  },
  {
    brand: "Balenciaga",
    name: "Track Sneaker",
    size: "42",
    price: 22000,
    category: "shoes",
    caption: "Архитектурный дизайн",
    imageUrl: img("Balenciaga", "e8e5e0", "444"),
    imageUrls: null,
    badge: "sold",
    telegramUrl: "https://t.me/pickmestore",
    featured: false,
    gender: "men",
    published: true,
    description: "Кроссовки Balenciaga Track. Многослойная конструкция, 176 деталей. Серый/оранжевый.",
    purchasePrice: 14000,
    sku: "BL-TRK-42",
    model: null,
  },
];

async function seed() {
  console.log(`Seeding ${products.length} products...`);

  for (const product of products) {
    await db.insert(productsTable).values(product);
  }

  console.log("Done! All products inserted.");
  await pool.end();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
